import { MonstieGene } from "../components/Gene";

export const TEST_BOARD: MonstieGene[] = [
  {
    geneName: "Smash Gene (S)",
    geneNumber: 17,
    attackType: "speed",
    elementType: "thunder",
    requiredLvl: 1,
    geneSize: 1,
    skill: {
      skillName: "Thunder Drop",
      skillType: "active",
      desc: "Deals light thunder damage to one enemy.",
    },
    possessedBy: { native: ["Tobi-Kadachi"], random: [] },
  },
  {
    geneName: "",
    geneNumber: -1,
    attackType: "",
    elementType: "",
    requiredLvl: -1,
    geneSize: -1,
    skill: { skillName: "", skillType: "", desc: "" },
    possessedBy: { native: [], random: [] },
  },
  {
    geneName: "Piercing Claws Gene (XL)",
    geneNumber: 12,
    attackType: "speed",
    elementType: "non-elemental",
    requiredLvl: 1,
    geneSize: 4,
    skill: {
      skillName: "Venom Sweep",
      skillType: "active",
      desc: "Deals heavy non-elemental damage to all enemies. Medium chance to inflict Poison for 3 turns.",
    },
    possessedBy: { native: ["Pink Rathian"], random: [] },
  },
  {
    geneName: "Whip Gene (S)",
    geneNumber: 1,
    attackType: "technical",
    elementType: "non-elemental",
    requiredLvl: 4,
    geneSize: 1,
    skill: {
      skillName: "Tail Spin",
      skillType: "active",
      desc: "Deals light non-elemental damage to all enemies.",
    },
    possessedBy: { native: ["Pukei-Pukei"], random: [] },
  },
  {
    geneName: "Whip Gene (L)",
    geneNumber: 3,
    attackType: "power",
    elementType: "fire",
    requiredLvl: 15,
    geneSize: 3,
    skill: {
      skillName: "Tail Spin Bomb",
      skillType: "active",
      desc: "Deals medium fire damage to all enemies. High chance to inflict Blastblight.",
    },
    possessedBy: { native: ["Uragaan"], random: [] },
  },
  {
    geneName: "",
    geneNumber: -1,
    attackType: "",
    elementType: "",
    requiredLvl: -1,
    geneSize: -1,
    skill: { skillName: "", skillType: "", desc: "" },
    possessedBy: { native: [], random: [] },
  },
  {
    geneName: "",
    geneNumber: -1,
    attackType: "",
    elementType: "",
    requiredLvl: -1,
    geneSize: -1,
    skill: { skillName: "", skillType: "", desc: "" },
    possessedBy: { native: [], random: [] },
  },
  {
    geneName: "Tackle Gene (M)",
    geneNumber: 14,
    attackType: "power",
    elementType: "ice",
    requiredLvl: 30,
    geneSize: 2,
    skill: {
      skillName: "Snowplow",
      skillType: "active",
      desc: "Deals medium ice damage to all enemies.",
    },
    possessedBy: { native: ["Gammoth"], random: [] },
  },
  {
    geneName: "Full Swing Gene (L)",
    geneNumber: 7,
    attackType: "power",
    elementType: "non-elemental",
    requiredLvl: 10,
    geneSize: 3,
    skill: {
      skillName: "Ruinous Tackle",
      skillType: "active",
      desc: "Deals heavy non-elemental damage to one enemy.",
    },
    possessedBy: { native: ["Nergigante"], random: [] },
  },
];
